### ISSUE TITLE
Case Insensitive not working in ALL TRNs as per spec

### ISSUE THREAD

**Issue by eharoldreyes** [eharoldreyes/nafithah-jointvision#1]
Case Insensitive not working in ALL TRNs
as per spec

**Comment by Dulvz** [comment]
to be check @eharoldreyes

**Comment by Dulvz** [comment]
"Case Insensitive Enhancements to ALL Datasets Please ensure processing for ALL COLUMNS RETURN BY ALL DATASETS are case sensitive managed for all platforms. Tested StaticPage and failed in LineData, other fields may also been effected. ListPage is not enabled with case senesetive.
Please make a global change to all retrieved columns."

**Comment by eharoldreyes** [comment]
@Dulvz kun please refer to this document regarding TRNs, https://drive.google.com/open?id=0B70lhGrAntOwazRQRFF4aXFSQ2c
