### ISSUE TITLE
Status Code not working as per the spec

### ISSUE THREAD

**Issue by eharoldreyes** [eharoldreyes/nafithah-jointvision#2]
Task #2, Status Code not working as per the spec.
-1 Not working, it is proceeding and not stopping
at the current position.

**Comment by Dulvz** [comment]
"STATUS DATASET
All Datasets returned from the database include the status in last table with two columns:
[CODE] = '0'  [DESCRIPTION] = 'SUCCESS'

-- MAY 3RD , 2016 TEAM VIEWER
--IF [CODE]=0 , PROCEED WITH NO MESSAGE TO THE USER
--IF [CODE] < 0 , DISPLAY MESSAGE TO USER, DO NOT PROCEED STAY ON THE SAME VIEW
-- IF [CODE] > 0 , PROCEED WITH MESSAGE TO THE USER

Please do not change current view before calling the TRN until you check CODE column. If not equal  '0', Pop-Up  the message in column [DESCRIPTION] to the user, and do not proceed with action., remain on the same view before calling the TRN. The text in [DESCRIPTION] column may have English or Arabic text as a communication message back to user using the Language flag passed in TRN calls."
